proxy: proxyMain.cpp proxyServerGET.cpp proxyServerCONNECT.cpp proxyServerPOST.cpp parseBuffer.hpp logger.hpp cache.hpp cacheRes.hpp exceptions.hpp
	g++ -o proxy proxyMain.cpp -pthread
.PHONY: clean
clean:
	rm -f proxy *~